openapi: "3.0.0"
info:
  version: 1.0.0
  title: Proverbs
  description: An API that accesses a proverb store
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8081/api
paths:
  /info:
    get:
      description: |
        Welcome message about the proverb application
      operationId: getInformation
      response:
        '200':
          description: information response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Information'

  /proverbs:
    get:
      description: |
        Returns all proverbs from the system that the user has access to
      operationId: findProverbs
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: proverb response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Proverb'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new proverb in the database. Duplicates are allowed
      operationId: addProverb
      requestBody:
        description: Proverb to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProverb'
      responses:
        '200':
          description: proverb response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Proverb'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /proverbs/{id}:
    get:
      description: Returns a proverb based on a single ID
      operationId: find proverb by id
      parameters:
        - name: id
          in: path
          description: ID of proverb to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: proverb response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Proverb'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: deletes a single proverb based on the ID supplied
      operationId: deleteProverb
      parameters:
        - name: id
          in: path
          description: ID of proverb to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: proverb deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Proverb:
      allOf:
        - $ref: '#/components/schemas/NewProverb'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64

    NewProverb:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string

    Information:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string